<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIudwxTm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIudwxTm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIudwxTm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIudwxTm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIudwxTm\App_KernelDevDebugContainer([
    'container.build_hash' => 'IudwxTm',
    'container.build_id' => 'd6840a46',
    'container.build_time' => 1590564446,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIudwxTm');
