<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ9LNNl4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ9LNNl4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ9LNNl4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ9LNNl4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ9LNNl4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q9LNNl4',
    'container.build_id' => '678b4dde',
    'container.build_time' => 1590573124,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ9LNNl4');
