<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPqZOM08\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPqZOM08/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPqZOM08.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPqZOM08\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPqZOM08\App_KernelDevDebugContainer([
    'container.build_hash' => 'PqZOM08',
    'container.build_id' => 'ea0f2bf9',
    'container.build_time' => 1590571942,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPqZOM08');
