<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'pilot_index' => [[], ['_controller' => 'App\\Controller\\Admin\\PilotController::index'], [], [['text', '/pilot/']], [], []],
    'pilot_new' => [[], ['_controller' => 'App\\Controller\\Admin\\PilotController::new'], [], [['text', '/pilot/new']], [], []],
    'pilot_show' => [['id'], ['_controller' => 'App\\Controller\\Admin\\PilotController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/pilot']], [], []],
    'pilot_edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\PilotController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/pilot']], [], []],
    'pilot_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\PilotController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/pilot']], [], []],
    'stable_index' => [[], ['_controller' => 'App\\Controller\\Admin\\StableController::index'], [], [['text', '/stable/']], [], []],
    'stable_new' => [[], ['_controller' => 'App\\Controller\\Admin\\StableController::new'], [], [['text', '/stable/new']], [], []],
    'stable_show' => [['id'], ['_controller' => 'App\\Controller\\Admin\\StableController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/stable']], [], []],
    'stable_edit' => [['id'], ['_controller' => 'App\\Controller\\Admin\\StableController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/stable']], [], []],
    'stable_delete' => [['id'], ['_controller' => 'App\\Controller\\Admin\\StableController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/stable']], [], []],
    'championship_index' => [[], ['_controller' => 'App\\Controller\\ChampionshipController::index'], [], [['text', '/championship/']], [], []],
    'championship_new' => [[], ['_controller' => 'App\\Controller\\ChampionshipController::new'], [], [['text', '/championship/new']], [], []],
    'championship_show' => [['id'], ['_controller' => 'App\\Controller\\ChampionshipController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/championship']], [], []],
    'championship_edit' => [['id'], ['_controller' => 'App\\Controller\\ChampionshipController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/championship']], [], []],
    'championship_delete' => [['id'], ['_controller' => 'App\\Controller\\ChampionshipController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/championship']], [], []],
];
